config/routes.rb
Rails.application.routes.draw do
  root to: "students#index"
  resources :students do
    member do
      get :assign_teachers
      post :create_teachers
      get :assign_subjects
      post :create_subjects
    end
  end

  resources :teachers do
    member do
      get :assign_students
      post :create_students
      get :assign_subjects
      post :create_subjects
    end
  end

  resources :subjects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  GENDER= ["Male", "Female", "Other"]
  LANGUAGE= ["Hindi", "English", "Other"]
  CATEGORY= ["General","OBC", "SC", "ST"]
  RELIGION= ["Hindu", "Muslim", "Other"]
  
  def full_name
    "#{first_name} #{middle_name} #{last_name}"
  end

  def full_address
    "#{address_line1}, #{address_line2}, #{city}, #{state}, #{country}, #{pin_code}"
  end
end

app/models/student.rb
class Student < ApplicationRecord
  has_and_belongs_to_many :subjects
  has_and_belongs_to_many :teachers
end
 

app/models/subject.rb
class Subject < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_and_belongs_to_many :subjects
  has_and_belongs_to_many :students
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, except: [:index, :create, :new]

  def new
    @student = Student.new
    @subjects = @student.subjects.new
  end
  
  def create
    @student = Student.new(student_params)
    
    if @student.save
      redirect_to students_path, notice: "Student created successfully."
    else
      render :new
    end
  end

  def index
    @students = Student.all
  end

  def show
    
  end

  def edit
    @subjects = @student.subjects
  end

  def update
    if @student.update_attributes(student_params)
      redirect_to students_path, notice: "Student updated successfully."
    else
      render :new, errors: @student.errors.full_messages
    end
  end
  
  def destroy
    if @student.destroy
      redirect_to root_path, notice: "Student-id #{@student.id} deleted successfully."
    else
      redirect_to :back, errors: "Something went wrong."
    end
  end

  def assign_teachers
    teacher_ids = @student.teachers.map(&:id)
    @teachers= Teacher.all.where.not(id: teacher_ids)
    redirect_to new_teacher_path, notice: "Teachers not found" unless @teachers.present?
  end

  def create_teachers
    teachers = Teacher.where(id: params[:teacher_ids])
    @student.teachers << teachers
    if @student.save
      redirect_to root_path, notice: "Teachers assigned successfully."
    else
      redirect_to :back, errors: "Something went wrong."
    end
  end

  def assign_subjects
    subject_ids = @student.subjects.map(&:id)
    @subjects= Subject.all.where.not(id: subject_ids)
    redirect_to new_subject_path, notice: "Subjects not found" unless @subjects.present?
  end

  def create_subjects
    subject_ids = params[:subject_ids]
    subjects = Subject.where(id: subject_ids)
    @student.subjects << subjects
    if @student.save
      redirect_to root_path, notice: "Subjects assigned successfully."
    else
      redirect_to :back, errors: "Something went wrong."
    end
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :middle_name, :last_name, :father_name, :gender,
                                  :mother_name, :class_roll_no, :date_of_birth, :birth_place, :language, :religion, :category, 
                                  :address_line1, :address_line2, :city, :state, :pin_code, :country, :phone, :email,
                                  :subjects_attributes => [:id, :name, :code]
                                )
  end

  def set_student
    @student = Student.find_by_id(params[:id])
    redirect_to root_path, notice: "Student not found." unless @student.present?
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, except: [:index, :create, :new]

  def new
    @subject = Subject.new
  end
  
  def create
    @subject = Subject.new(subject_params)
    
    if @subject.save
      redirect_to subjects_path, notice: "Subject created successfully."
    else
      render :new
    end
  end

  def index
    @subjects = Subject.all
  end

  def show
    
  end

  def edit
  end

  def update
    if @subject.update_attributes(subject_params)
      redirect_to subjects_path, notice: "Subject updated successfully."
    else
      render :new, errors: @subject.errors.full_messages
    end
  end
  
  def destroy
    if @subject.destroy
      redirect_to root_path, notice: "Subject-id #{@subject.id} deleted successfully."
    else
      redirect_to :back, errors: "Something went wrong."
    end
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :code)
  end

  def set_subject
    @subject = Subject.find_by_id(params[:id])
    redirect_to root_path, notice: "Subject not found." unless @subject.present?
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, except: [:index, :create, :new]

  def new
    @teacher = Teacher.new
    @subjects = @teacher.subjects.new
  end
  
  def create
    @teacher = Teacher.new(teacher_params)
    
    if @teacher.save
      redirect_to teachers_path, notice: "teacher created successfully."
    else
      render :new
    end
  end

  def index
    @teachers = Teacher.all
  end

  def show
    
  end

  def edit
    @subjects = @teacher.subjects
  end

  def update
    if @teacher.update_attributes(teacher_params)
      redirect_to teachers_path, notice: "teacher updated successfully."
    else
      render :new, errors: @teacher.errors.full_messages
    end
  end
  
  def destroy
    if @teacher.destroy
      redirect_to root_path, notice: "teacher-id #{@teacher.id} deleted successfully."
    else
      redirect_to :back, errors: "Something went wrong."
    end
  end

  def assign_students
    student_ids = @teacher.students.map(&:id)
    @students= Student.all.where.not(id: student_ids)
    redirect_to new_student_path, notice: "Teachers not found" unless @students.present?
  end

  def create_students
    students = Student.where(id:  params[:student_ids])
    @teacher.students << students
    if @teacher.save
      redirect_to root_path, notice: "Students assigned successfully."
    else
      redirect_to :back, errors: "Something went wrong."
    end
  end

  def assign_subjects
    subject_ids = @teacher.subjects.map(&:id)
    @subjects= Subject.all.where.not(id: subject_ids)
    redirect_to new_subject_path, notice: "Subjects not found" unless @subjects.present?
  end

  def create_subjects
    subjects = Subject.where(id: params[:subject_ids])
    @teacher.subjects << subjects
    if @teacher.save
      redirect_to root_path, notice: "Subjects assigned successfully."
    else
      redirect_to :back, errors: "Something went wrong."
    end
  end

  private

  def teacher_params
    params.require(:teacher).permit(:first_name, :middle_name, :last_name, :address, 
                                    :qualification, :city, :state, :pin_code, :country,
                                    :phone, :email, :gender,
                                  :subjects_attributes => [:id, :name, :code]
                                )
  end

  def set_teacher
    @teacher = Teacher.find_by_id(params[:id])
    redirect_to root_path, notice: "teacher not found." unless @teacher.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/students/assign_subjects.html.erb
<%= form_for @student, url: create_subjects_student_path(@student.id), method: :post, :html => { :class => "form-horizontal student" } do |f| %>

  <% if @student.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= select_tag "subject_ids", options_from_collection_for_select(@subjects, "id", "name"), prompt: "Select something", multiple: true, class: 'form-control' %>
    </div>
    <%=f.error_span(:first_name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Assign Subjects", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                students_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

<br>
<%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn btn-default'  %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_subject_path,
            :class => 'btn btn-primary' %>

app/views/students/assign_teachers.html.erb
<%= form_for @student, url: create_teachers_student_path(@student.id), method: :post, :html => { :class => "form-horizontal student" } do |f| %>

  <% if @student.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :teacher_ids, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= select_tag "teacher_ids", options_from_collection_for_select(@teachers, "id", "full_name"), prompt: "Select something", multiple: true, class: 'form-control' %>
    </div>
    <%=f.error_span(:first_name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Add Teachers", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                students_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

<br>
<%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn btn-default'  %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_teacher_path,
            :class => 'btn btn-primary' %>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/index.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped" border="1">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:father_name) %></th>
      <th><%= model_class.human_attribute_name(:mother_name) %></th>
      <th><%= model_class.human_attribute_name(:class_roll_no) %></th>
      <th><%= model_class.human_attribute_name(:date_of_birth) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:birth_place) %></th>
      <th><%= model_class.human_attribute_name(:language) %></th>
      <th><%= model_class.human_attribute_name(:religion) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%if @students.present? %>
      <% @students.each do |student| %>
        <tr>
          <td><%= link_to student.id, student_path(student) %></td>
          <td><%= student.full_name %></td>
          <td><%= student.father_name %></td>
          <td><%= student.mother_name %></td>
          <td><%= student.class_roll_no %></td>
          <td><%= student.date_of_birth %></td>
          <td><%= student.gender %></td>
          <td><%= student.birth_place %></td>
          <td><%= student.language %></td>
          <td><%= student.religion %></td>
          <td><%= student.category %></td>
          <td><%= student.full_address %></td>
          <td><%= student.phone %></td>
          <td><%= student.email %></td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        student_path(student), :class => 'btn btn-default btn-xs' %>
            <%= link_to "Assign teachers", assign_teachers_student_path(student),
              :class => 'btn btn-default btn-xs' %>
              <%= link_to "Assign subjects", assign_subjects_student_path(student),
              :class => 'btn btn-default btn-xs' %>
          </td>
        </tr>
      <% end %>
    <%else%>
      <tr><td colspan="15" align="center"> No records</td></tr>
    <%end%>
  </tbody>
</table>

<br>
          

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_path,
            :class => 'btn btn-primary' %>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<table class="table table-striped" border="1">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:father_name) %></th>
      <th><%= model_class.human_attribute_name(:mother_name) %></th>
      <th><%= model_class.human_attribute_name(:class_roll_no) %></th>
      <th><%= model_class.human_attribute_name(:date_of_birth) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:birth_place) %></th>
      <th><%= model_class.human_attribute_name(:language) %></th>
      <th><%= model_class.human_attribute_name(:religion) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%if @student.present? %>
      <tr>
        <td><%= link_to @student.id, student_path(@student) %></td>
        <td><%= @student.full_name %></td>
        <td><%= @student.father_name %></td>
        <td><%= @student.mother_name %></td>
        <td><%= @student.class_roll_no %></td>
        <td><%= @student.date_of_birth %></td>
        <td><%= @student.gender %></td>
        <td><%= @student.birth_place %></td>
        <td><%= @student.language %></td>
        <td><%= @student.religion %></td>
        <td><%= @student.category %></td>
        <td><%= @student.full_address %></td>
        <td><%= @student.phone %></td>
        <td><%= @student.email %></td>
        <td>
          <%= link_to "Student List",
                      students_path, :class => 'btn btn-default btn-xs' %>
          <%= link_to "Assign teachers", assign_teachers_student_path(@student),
            :class => 'btn btn-default btn-xs' %>
            <%= link_to "Assign subjects", assign_subjects_student_path(@student),
            :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <%else%>
      <tr><td colspan="15" align="center"> No records</td></tr>
    <%end%>
  </tbody>
</table>

<%- model_class = Student -%>
<div class="page-header">
  <h1>Student's teachers</h1>
</div>
<table class="table table-striped" border="1">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:qualification) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%if @student.teachers.present? %>
      <% @student.teachers.each do |teacher| %>
        <tr>
          <td><%= link_to teacher.id, teacher_path(teacher) %></td>
          <td><%= teacher.full_name %></td>
          <td><%= teacher.gender %></td>
          <td><%= teacher.email %></td>
          <td><%= teacher.phone %></td>
          <td><%= teacher.full_address %></td>
          <td><%= teacher.qualification %></td>
          <td>
            <%= link_to "Teacher Detail", teacher_path(teacher),
              :class => 'btn btn-default btn-xs' %>
          </td>
        </tr>
      <% end %>
    <%else%>
      <tr><td colspan="8" align="center"> No records</td></tr>
    <%end%>
  </tbody>
</table>

<%- model_class = Subject -%>
<div class="page-header">
  <h1>Student's subjects </h1>
</div>
<table class="table table-striped" border="1">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%if @student.subjects.present? %>
      <%  @student.subjects.each do |subject| %>
        <tr>
          <td><%= link_to subject.id, subject_path(subject) %></td>
          <td><%= subject.name %></td>
          <td><%= subject.code %></td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        subjects_path(subject), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_subject_path(subject), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        subject_path(subject),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
    <%else%>
      <tr>
        <td colspan="4" align="center"> No records</td>
        <td>
          <%= link_to t('.new', :default => t("helpers.links.new")),
                    new_teacher_path,
                    :class => 'btn btn-primary' %>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>

<br>

<%= link_to t('.back', :default => t("helpers.links.back")),
              students_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/subjects/edit.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subjects/new.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/teachers/edit.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/teachers/index.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped" border="1">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:qualification) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%if @teachers.present? %>
      <% @teachers.each do |teacher| %>
        <tr>
          <td><%= link_to teacher.id, teacher_path(teacher) %></td>
          <td><%= teacher.full_name %></td>
          <td><%= teacher.gender %></td>
          <td><%= teacher.email %></td>
          <td><%= teacher.phone %></td>
          <td><%= teacher.full_address %></td>
          <td><%= teacher.qualification %></td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.show")),teacher_path(teacher),
            :class => 'btn btn-primary' %>

            <%= link_to "Assign students", assign_students_teacher_path(teacher),
              :class => 'btn btn-default btn-xs' %>
            <%= link_to "Assign subjects", assign_subjects_teacher_path(teacher),
              :class => 'btn btn-default btn-xs' %>
          </td>
        </tr>
      <% end %>
    <%else%>
      <tr><td colspan="14" align="center"> No records</td></tr>
    <%end%>
  </tbody>
</table>
<br>

<%= link_to "Back", students_path, :class => 'btn btn-default btn-xs' %>


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_teacher_path,
            :class => 'btn btn-primary' %>

app/views/teachers/show.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<table class="table table-striped" border="1">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:qualification) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%if @teacher.present? %>
        <tr>
          <td><%= link_to @teacher.id, teacher_path(@teacher) %></td>
          <td><%= @teacher.full_name %></td>
          <td><%= @teacher.gender %></td>
          <td><%= @teacher.email %></td>
          <td><%= @teacher.phone %></td>
          <td><%= @teacher.full_address %></td>
          <td><%= @teacher.qualification %></td>
          <td>
            <%= link_to t('.new', :default => t("helpers.links.new")),
            new_teacher_path,
            :class => 'btn btn-primary' %>

            <%= link_to "Assign students", assign_students_teacher_path(@teacher),
              :class => 'btn btn-default btn-xs' %>
            <%= link_to "Assign subjects", assign_subjects_teacher_path(@teacher),
              :class => 'btn btn-default btn-xs' %>
          </td>
        </tr>
    <%else%>
      <tr><td colspan="7" align="center"> No records</td></tr>
    <%end%>
  </tbody>
</table>

<%- model_class = Teacher -%>
<div class="page-header">
  <h1>Teacher's students</h1>
</div>
<table class="table table-striped" border="1">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:father_name) %></th>
      <th><%= model_class.human_attribute_name(:mother_name) %></th>
      <th><%= model_class.human_attribute_name(:class_roll_no) %></th>
      <th><%= model_class.human_attribute_name(:date_of_birth) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:birth_place) %></th>
      <th><%= model_class.human_attribute_name(:language) %></th>
      <th><%= model_class.human_attribute_name(:religion) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
    </tr>
  </thead>
  <tbody>
    <%if @teacher.students.present? %>
      <% @teacher.students.each do |student| %>
        <tr>
          <td><%= link_to student.id, student_path(student) %></td>
          <td><%= student.full_name %></td>
          <td><%= student.father_name %></td>
          <td><%= student.mother_name %></td>
          <td><%= student.class_roll_no %></td>
          <td><%= student.date_of_birth %></td>
          <td><%= student.gender %></td>
          <td><%= student.birth_place %></td>
          <td><%= student.language %></td>
          <td><%= student.religion %></td>
          <td><%= student.category %></td>
          <td><%= student.full_address %></td>
          <td><%= student.phone %></td>
          <td><%= student.email %></td>
        </tr>
      <% end %>
    <%else%>
      <tr><td colspan="14" align="center"> No records</td></tr>
    <%end%>
  </tbody>
</table>

<%- model_class = Subject -%>
<div class="page-header">
  <h1>Teacher's subjects </h1>
</div>
<table class="table table-striped" border="1">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%if @teacher.subjects.present? %>
      <%  @teacher.subjects.each do |subject| %>
        <tr>
          <td><%= link_to subject.id, subject_path(subject) %></td>
          <td><%= subject.name %></td>
          <td><%= subject.code %></td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        subject_path(subject), :class => 'btn btn-default btn-xs' %>            
            </td>
        </tr>
      <% end %>
    <%else%>
      <tr>
        <td colspan="3" align="center"> No records</td>
        <td><%= link_to t('.new', :default => t("helpers.links.new")),
            new_subject_path,
            :class => 'btn btn-primary' %></td> 
       </tr>
    <%end%>
  </tbody>
</table>

<%= link_to t('.back', :default => t("helpers.links.back")),
              teachers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_teacher_path(@teacher), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              teacher_path(@teacher),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>